input.onButtonPressed(Button.A, function () {
    music.play(music.stringPlayable("C E F A B G E C ", 120), music.PlaybackMode.UntilDone)
})
input.onButtonPressed(Button.B, function () {
    music.play(music.stringPlayable("C E G D F D A B ", 120), music.PlaybackMode.UntilDone)
})
basic.showIcon(IconNames.Happy)
basic.showString("Hallo! Ich bin micro:bit!")
basic.showString("Druecke gerne A oder B!")
basic.pause(1000)
basic.clearScreen()
basic.forever(function () {
    led.plot(0, 2)
    basic.pause(700)
    led.plot(1, 2)
    basic.pause(700)
    led.plot(2, 2)
    basic.pause(700)
    led.plot(3, 2)
    basic.pause(700)
    led.plot(4, 2)
    basic.pause(700)
    led.unplot(0, 2)
    basic.pause(700)
    led.unplot(1, 2)
    basic.pause(700)
    led.unplot(2, 2)
    basic.pause(700)
    led.unplot(3, 2)
    basic.pause(700)
    led.unplot(4, 2)
    basic.pause(700)
    led.plot(2, 4)
    basic.pause(700)
    led.plot(2, 3)
    basic.pause(700)
    led.plot(2, 2)
    basic.pause(700)
    led.plot(2, 1)
    basic.pause(700)
    led.plot(2, 0)
    basic.pause(700)
    led.unplot(2, 4)
    basic.pause(700)
    led.unplot(2, 3)
    basic.pause(700)
    led.unplot(2, 2)
    basic.pause(700)
    led.unplot(2, 1)
    basic.pause(700)
    led.unplot(2, 0)
    basic.pause(700)
})
